; Set up PHP for prod
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
html_errors = Off

; Memory
memory_limit = 128M

; Execution time
max_execution_time = 30
max_input_time = 60

; File downloading
upload_max_filesize = 20M
post_max_size = 25M

; Set up session for security
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
session.gc_probability = 1
session.gc_divisor = 1000

; Security
expose_php = Off
allow_url_fopen = Off
allow_url_include = Off

; Set up for production environment
default_socket_timeout = 60
auto_prepend_file =
auto_append_file =

; Switch off the potentially danger functions
disable_functions = exec,passthru,shell_exec,system,proc_open,popen
