; Set up PHP for dev
display_errors = On
display_startup_errors = On
log_errors = On
error_reporting = E_ALL
html_errors = On

; Memory
memory_limit = 256M

; Execution time
max_execution_time = 30
max_input_time = 60

; File downloading
upload_max_filesize = 20M
post_max_size = 25M

; Session set up
session.gc_probability = 1
session.gc_divisor = 1000

; Expose PHP version
expose_php = On

; Set up for debugging
default_socket_timeout = 60
