parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Domain/ValueObject/'
            - '../src/Kernel.php'

    App\Application\UseCase\GetFullBasketUseCase:
        arguments:
            $responseAssembler: '@App\Application\Assembler\Response\GetFullBasketResponseAssembler'