services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  App\Application\Assembler\Response\GetFullBasketResponseAssembler:
    public: true

  App\Domain\Service\DeliveryCostCalculator:
    public: true