parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Domain/ValueObject/'
            - '../src/Kernel.php'

    _instanceof:
        # all services implementing the CommandHandlerInterface
        # will be registered on the command.bus bus
        App\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        # while those implementing QueryHandlerInterface will be
        # registered on the query.bus bus
        App\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    # Middlewares
    App\Infrastructure\Middleware\ExceptionFormatterMiddleware:
        arguments:
            $env: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Usecases
    App\Application\UseCase\GetFullBasketUseCase:
        arguments:
            $responseAssembler: '@App\Application\Assembler\Response\GetFullBasketResponseAssembler'

    App\Application\Query\FindShortBasket\FindShortBasketQueryHandler:
        arguments:
            $shortBasketResponseAssembler: '@App\Application\Assembler\Response\ShortBasketResponseAssembler'

    # HTTP API
    App\Infrastructure\Http\Api\SymfonyClientShopApi:
        class: App\Infrastructure\Http\Api\SymfonyClientShopApi
        arguments:
            $validStatuses: [ 200 ]
            $options: '%config_shop_api%'

    App\Infrastructure\Http\Api\SymfonyClientDeliverySlotApi:
        class: App\Infrastructure\Http\Api\SymfonyClientDeliverySlotApi
        arguments:
            $validStatuses: [ 200 ]
            $options: '%config_delivery_slop_api%'
