networks:
  order-processing:
    name: order-processing
    driver: bridge

services:
  order-proc-fpm:
    container_name: order-proc-fpm
    networks:
      - order-processing
    build:
      context: ../../
      dockerfile: ./.deployment/docker/php-fpm/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./../../:/var/www/order-processing

  order-proc-nginx:
    container_name: order-proc-nginx
    networks:
      - order-processing
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        PHP_UPSTREAM_CONTAINER: ${PHP_UPSTREAM_CONTAINER}
        PHP_UPSTREAM_PORT: ${PHP_UPSTREAM_PORT}
    environment:
      PHP_UPSTREAM_CONTAINER: ${PHP_UPSTREAM_CONTAINER}
      PHP_UPSTREAM_PORT: ${PHP_UPSTREAM_CONTAINER}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../../:/var/www/order-processing:rw
    depends_on:
      - order-proc-fpm

  order-proc-postgres:
    container_name: order-proc-postgres
    networks:
      - order-processing
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_order_proc_data:/var/lib/postgresql/data:rw
volumes:
  db_order_proc_data:
